In [1]:
import pandas as pd
import numpy as np
import os
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
sent = ["the glass of milk",
        "the glass of juice",
        "the cup of tea",
        "I am a good boy",
        "I am a good developer",
        "understand the meaning of words",
        "your videos are good"]

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [16]:
voc_size = 10000
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[5725, 2742, 4169, 6788],
 [5725, 2742, 4169, 7802],
 [5725, 2822, 4169, 2497],
 [3775, 4728, 4442, 7351, 5326],
 [3775, 4728, 4442, 7351, 4616],
 [8187, 5725, 6339, 4169, 6877],
 [5966, 100, 5813, 7351]]

In [37]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [38]:
sent_len = 8
embeded_docs = pad_sequences(one_hot_rep,maxlen=sent_len,padding="post")
embeded_docs

array([[5725, 2742, 4169, 6788,    0,    0,    0,    0],
       [5725, 2742, 4169, 7802,    0,    0,    0,    0],
       [5725, 2822, 4169, 2497,    0,    0,    0,    0],
       [3775, 4728, 4442, 7351, 5326,    0,    0,    0],
       [3775, 4728, 4442, 7351, 4616,    0,    0,    0],
       [8187, 5725, 6339, 4169, 6877,    0,    0,    0],
       [5966,  100, 5813, 7351,    0,    0,    0,    0]], dtype=int32)

In [42]:
dim = 10
voc_size=10000
sent_len = 8

In [43]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_len))
model.compile("adam","mse")

In [44]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step


array([[[-2.6169349e-02, -1.1927165e-02, -2.4735559e-02, -3.4502633e-03,
         -3.9577484e-04,  3.2149289e-02,  2.7341757e-02, -3.4975469e-02,
          1.7118108e-02, -3.5256874e-02],
        [-3.7152339e-02,  2.5684547e-02,  4.1709732e-02,  1.5621457e-02,
         -6.9149509e-03,  2.6029717e-02, -2.1027446e-02, -4.4671774e-02,
          6.9827810e-03,  5.4507144e-03],
        [ 2.6009943e-02, -8.3568469e-03,  1.7182659e-02,  1.3130393e-02,
          3.3902612e-02, -3.4195445e-02,  4.1928027e-02,  4.0359858e-02,
         -4.5357514e-02,  4.1924868e-02],
        [ 2.3893367e-02, -2.9060280e-02,  1.9118000e-02, -1.0545649e-02,
          3.8230304e-02,  1.2410261e-02, -7.9052933e-03,  3.5035823e-02,
         -2.5297940e-02, -2.7982010e-02],
        [-1.2462068e-02, -4.5279395e-02,  3.9813746e-02,  1.6764525e-02,
         -1.2058843e-02, -4.4810653e-02,  4.3620918e-02, -4.4398259e-02,
         -2.5268996e-02,  1.2289595e-02],
        [-1.2462068e-02, -4.5279395e-02,  3.9813746e-02,  1.

In [47]:
model.predict(embeded_docs)[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([-0.02616935, -0.01192717, -0.02473556, -0.00345026, -0.00039577,
        0.03214929,  0.02734176, -0.03497547,  0.01711811, -0.03525687],
      dtype=float32)